#Dropdown list
selectInput(inputId = "variable", #the name is up to you, must be unique
            label = "Subject: ", #labeling of dropdownlist
            choices = c("English" = "ENGLISH",
                        "Maths" = "MATHS",
                        "Science" = "SCIENCE"),
            selected = "ENGLISH"), #Uppercase is original data

#Slider input
sliderInput(inputId = "bin", #the name is up to you, must be unique
            label = "No. of bins",
            min = 5,
            max = 20,
            value = c(10)),

#Single checkbox
checkboxInput(inputId = "show_data",
              label = "Show data table",
              value = TRUE)

#https://shiny.rstudio.com/articles/plot-interaction.html to interact with
#both STATIC plots and plots generated by ggplot2
#Plot click, double-click, hover, brush

ui <- basicPage(
  plotOutput("plot1",
             click = "plot_click",
             dblclick = "plot_dblclick",
             hover = "plot_hover",
             brush = "plot_brush"
  ),
  verbatimTextOutput("info")

  server <- function(input, output) {
    output$plot1 <- renderPlot({
      plot(mtcars$wt, mtcars$mpg)
    })
    
    output$info <- renderText({
      xy_str <- function(e) {
        if(is.null(e)) return("NULL\n")
        paste0("x=", round(e$x, 1), " y=", round(e$y, 1), "\n")
      }
      xy_range_str <- function(e) {
        if(is.null(e)) return("NULL\n")
        paste0("xmin=", round(e$xmin, 1), " xmax=", round(e$xmax, 1), 
               " ymin=", round(e$ymin, 1), " ymax=", round(e$ymax, 1))
      }
      
      paste0(
        "click: ", xy_str(input$plot_click),
        "dblclick: ", xy_str(input$plot_dblclick),
        "hover: ", xy_str(input$plot_hover),
        "brush: ", xy_range_str(input$plot_brush)
      )
    })
  }