---
title: "Project Proposal"
description: |
  Our proposed approach to solve VAST Challenge 2021: Mini-Challenge 2
author:
  - name: Archie DOLIT, Kevin SUNGA, Syiqah TAHA
    url: https://scis.smu.edu.sg/master-it-business
    affiliation: School of Computing and Information Systems, Singapore Management University
    affiliation_url: https://scis.smu.edu.sg/
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# 1. Overview

VAST Challenge 2021 mini-challenge 2 includes various csv and geospatial files providing clues on the preparation of Protector of Kronos (POK) in kidnapping GASTech employees.  

# 2. Project Motivation

Using the data in mini-challenge 2, the objective of the project is to analyze the movement and tracking of GAStech employees via the vehicle GPS data. The credit card purchases, and loyalty usage data will be used to identity anomalies in the financial transactions.  

# 3. Data

From mini-challenge 2, we will join the credit card and loyalty data using the timestamp, location, and price. It will help us determine the most popular locations. The additional information from the loyalty and last4accum will hopefully detect possible anomalies.

The GPS tracking data projected on the geospatial files will help us analyse the movements of different employees. Adding the vehicle data to the credit card and loyalty data will hopefully uncover discrepancies.
The car assignment, location indicated in credit card, loyalty, and GPS data will help to infer the owners of the credit cards.

The possible anomalies from the credit card purchases and discrepancies from the vehicle movements will provide evidence on the suspicious activities.

# 4. Relevant Works

* 4.1 [Georgia Institute of Technology](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/Georgia Institute of Technology/)
  + They created interactive 3D map visualizations of where individuals are.
  + They created a map of GPS data.
  + There are many data points. It seems challenging to figure out what’s worth paying attention to.

* 4.2 [Virginia Tech](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/Virginia Tech/)
  + They use a framework called POI or points of interest which is roughly defined as having spent more than  5 mins at the location.
  
* 4.3 [Central South University](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/Central South University)
  + Good visualisation, Intuitive and easy to understand 

* 4.4 [Fraunhofer IAIS and City University London](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/Fraunhofer IAIS and City University London)
  + The semantic space is a good tool to show different relationships 

* 4.5 [Middlesex University](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/Middlesex University)
  + Good use of patterns of life atlas tool 
  + The car id is selectable and does not clutter the visualisation

* 4.6 [Nanyang Technological University Singapore](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/Nanyang Technological University Singapore)
  + Use basic tools like excel to perform the visualisation
  + Not interactive

* 4.7 [University of Konstanz](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/University of Konstanz)
  + Shows a very complex looking data transformation to derive insights
  
* 4.8 [Tennessee Tech University](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/Tennessee Tech University)
  + Not very useful. It did not discuss how insights were derived 
  
* 4.9 [CERTH-ITI](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/CERTH-ITI)
  + Used proprietary tool
  + No actual mapping
  + Display credit card transactions over time in a day to determine routine (day v time, user v day, day v location, user v location)

* 4.10 [Georgia Institute of Technology](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/Georgia Institute of Technology)
  + Used D3, Matlab (Analytics-based)
  + Not mapped to Abila 
  + Tracking data (lines) and spending data (circles)
  + Matrix view
  + Timeline view
  + 3D Space-time cube view --> coloured lines overlap so difficult to follow trail
  + Identified Lucas Alcazar was not present when high-value purchase was made at Frydo’s Autosupply
  
  + Used proprietary web-based tool
  + To map movement on Abila
  + By car/person
  + By time period
  
  + Heatmap of employee vs transactions --> Used to confirm other findings

* 4.11 [International Institute of Information Technology Hyderabad](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/International Institute of Information Technology Hyderabad)
  + Used geotools.org, QGIS, D3.js
  + Simple frequency count of transactions (credit card and loyalty card) by date to detect patterns
  + Simple frequency count of transactions (credit card and loyalty card) by employee name/ shop to detect patterns
  + Look at car GPS pattern/ frequency throughout the day and by date

* 4.12 [Peking University](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/Peking University)
  + Used Python, D3.js, QGIS
  + Perform hierarchical  clustering on car owners based on general car pattern on weekday-weekend.
  + Animated temporal view of car path
  + Periodic time brush + event time line
  + Spatial temporal exploration design
  + Very neat summary of location and event timeline (24-hr ring)
  + Interactive selection of location to show 24-hr timeline


* 4.13 [Purdue University](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/Purdue University)
  + Uses HTML5, CSS, SVG, JavaScripts, jQuery, PHP, MySQL and D3 to query, compute, serve and visualize data.
  + Dodeca-Rings Map
  + Similar to Peking Uni’s spatial temporal exploration design + multiple rings for multiple cars
  + Social relationship matrix
  + More meetings, darker color
  + Simple concept

* 4.14 [University of Buenos Aires - Alcoser](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/University of Buenos Aires - Alcoser)
  + Used Tableau, Excel, Sql Server 2012, Spss, Qgis
  + Simple frequency count of transactions by date to detect patterns
  
* 4.15 [University of Buenos Aires - Croceri](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/University of Buenos Aires - Croceri)
  + Used Tableau 8.1, QGis, Excel 2010, SAS Enterprise Guide
  + Heatmap for car patterns/frequency
  + Treemap of purchases at different times of the day
  + Bubble graphs (different sizes) of purchases by employee
  + Boxplot of purchases at each supplier
  + Scatterplot of speed to identify outliers

* 4.16 [University of California, Davis](http://visualdata.wustl.edu/varepository/VAST Challenge 2014/challenges/MC2 - Patterns of Life Analysis/entries/University of California, Davis)
  + Apart from plotting car path, there’s barely any data analytics performed

# 5. Approach and Storyboard


# 6. R Packages
* [Shiny](https://shiny.rstudio.com/)
  + Create R shiny interfaces
  
* [shinyWidgets](https://cran.r-project.org/web/packages/shinyWidgets/index.html)
  + Custom input widgets for Shiny App

* [tidyverse](https://www.tidyverse.org/)
  + Collection of R packages for data analysis
  
* [dplyr](https://cran.r-project.org/web/packages/tidyr/index.html)
  + Tools for Cleaning the data such as Splitting, Applying and Combining Data
  
* [ggplot2](https://cran.r-project.org/web/packages/ggplot2/index.html)
  + Create graphics and charts
  
* [plotly](https://cran.r-project.org/web/packages/plotly/index.html)
  + Create interactive graphics and charts

* [Sf](https://cran.r-project.org/web/packages/sf/index.html)
  + Provides a standardized way to encode spatial vector data

* [Tmap](https://cran.r-project.org/web/packages/tmap/index.html)
  + Thematic maps to visualize spatial data distribution including choropleths and bubble maps

* [Rgdal](https://cran.r-project.org/web/packages/rgdal/index.html)
   + Provides bindings for the 'Geospatial' Data Abstraction Library


# 7. Team Members

* [Archie Quiambao DOLIT](https://www.linkedin.com/in/adolit/)

* [Kevin Magic Rialubin SUNGA](https://www.linkedin.com/in/kevin-sunga/)

* [Nurulasyiqah Mohammad TAHA](https://www.linkedin.com/in/nurulasyiqah-md-taha/)